version: "3.7"

services:
  app:
    container_name: app
    environment:
      - MONGO_DOCKER_URI=mongodb://mongo:27017
    ports:
      - "3000:3000"
    command: npm run dev
    build: ./
    working_dir: /app
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-seed:
    build: ./mongo-seed
